# Generated by Django 4.2.4 on 2023-08-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="party",
            options={"ordering": ("party_no",)},
        ),
        migrations.CreateModel(
            name="ResultSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("constituencies_count", models.IntegerField(default=0)),
                ("party_list_count", models.IntegerField(default=0)),
                ("party", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analysis.party")),
            ],
        ),
    ]
